package mx.com.ikusi.brms.model;


import com.thoughtworks.xstream.annotations.XStreamAlias;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Device implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "sysId")
   @XStreamAlias("sys_id")
   private java.lang.String sysId;
   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "ipAddress")
   @XStreamAlias("ip_address")
   private java.lang.String ipAddress;
   @org.kie.api.definition.type.Label(value = "category")
   private java.lang.String category;
   @org.kie.api.definition.type.Label(value = "subcategory")
   private java.lang.String subcategory;
   @org.kie.api.definition.type.Label(value = "sysClassName")
    @XStreamAlias("sys_class_name")
   private java.lang.String sysClassName;
   @org.kie.api.definition.type.Label(value = "serialNumber")
   @XStreamAlias("serial_number")
   private java.lang.String serialNumber;

   public Device()
   {
   }

   public java.lang.String getSysId()
   {
      return this.sysId;
   }

   public void setSysId(java.lang.String sysId)
   {
      this.sysId = sysId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getIpAddress()
   {
      return this.ipAddress;
   }

   public void setIpAddress(java.lang.String ipAddress)
   {
      this.ipAddress = ipAddress;
   }

   public java.lang.String getCategory()
   {
      return this.category;
   }

   public void setCategory(java.lang.String category)
   {
      this.category = category;
   }

   public java.lang.String getSubcategory()
   {
      return this.subcategory;
   }

   public void setSubcategory(java.lang.String subcategory)
   {
      this.subcategory = subcategory;
   }

   public java.lang.String getSysClassName()
   {
      return this.sysClassName;
   }

   public void setSysClassName(java.lang.String sysClassName)
   {
      this.sysClassName = sysClassName;
   }

   public java.lang.String getSerialNumber()
   {
      return this.serialNumber;
   }

   public void setSerialNumber(java.lang.String serialNumber)
   {
      this.serialNumber = serialNumber;
   }

   public Device(java.lang.String sysId, java.lang.String name,
         java.lang.String ipAddress, java.lang.String category,
         java.lang.String subcategory, java.lang.String sysClassName,
         java.lang.String serialNumber)


   {
      this.sysId = sysId;
      this.name = name;
      this.ipAddress = ipAddress;
      this.category = category;
      this.subcategory = subcategory;
      this.sysClassName = sysClassName;
      this.serialNumber = serialNumber;
   } 

    

}