package mx.com.ikusi.brms.model;

import com.thoughtworks.xstream.annotations.XStreamAsAttribute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("context")
   private java.lang.String context;
   @org.kie.api.definition.type.Label("severity")
   private java.lang.String severity;
   @org.kie.api.definition.type.Label("time")
   private String time;
   @org.kie.api.definition.type.Label("colector")
   private java.lang.String colector;

   @org.kie.api.definition.type.Label("uei")
   private java.lang.String uei;

   @org.kie.api.definition.type.Label("customer")
   private java.lang.String customer;

   private java.lang.String callerid;

   public Event()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getContext()
   {
      return this.context;
   }

   public void setContext(java.lang.String context)
   {
      this.context = context;
   }

   public java.lang.String getSeverity()
   {
      return this.severity;
   }

   public void setSeverity(java.lang.String severity)
   {
      this.severity = severity;
   }

   public java.lang.String getColector()
   {
      return this.colector;
   }

   public void setColector(java.lang.String colector)
   {
      this.colector = colector;
   }

   public java.lang.String getTime()
   {
      return this.time;
   }

   public void setTime(java.lang.String time)
   {
      this.time = time;
   }

   public java.lang.String getUei()
   {
      return this.uei;
   }

   public void setUei(java.lang.String uei)
   {
      this.uei = uei;
   }

   public java.lang.String getCustomer()
   {
      return this.customer;
   }

   public void setCustomer(java.lang.String customer)
   {
      this.customer = customer;
   }

   public java.lang.String getCallerid()
   {
      return this.callerid;
   }

   public void setCallerid(java.lang.String callerid)
   {
      this.callerid = callerid;
   }

   public Event(java.lang.String name, java.lang.String context,
         java.lang.String severity, java.lang.String time,
         java.lang.String colector, java.lang.String uei,
         java.lang.String customer, java.lang.String callerid)
   {
      this.name = name;
      this.context = context;
      this.severity = severity;
      this.time = time;
      this.colector = colector;
      this.uei = uei;
      this.customer = customer;
      this.callerid = callerid;
   }

}