package mx.com.ikusi.brms.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamImplicit;

@XStreamAlias("metrics")
public class Metrics implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "metrics")
   @XStreamImplicit(itemFieldName = "metric")
   private java.util.List<Metric> metrics;

   public Metrics()
   {
   }

   public java.util.List<Metric> getMetrics()
   {
      return this.metrics;
   }

   public void setMetrics(java.util.List<Metric> metrics)
   {
      this.metrics = metrics;
   }

   public Metrics(java.util.List<Metric> metrics)
   {
      this.metrics = metrics;
   }

}
