package mx.com.ikusi.brms.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import com.thoughtworks.xstream.annotations.XStreamAlias;
 
 
@XStreamAlias("metric")
public class Metric implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "value")
   private java.lang.String value;

   public Metric()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public Metric(java.lang.String name, java.lang.String value)
   {
      this.name = name;
      this.value = value;
   }

}