package mx.com.ikusi.brms.model;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class Nodo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String sys_id;
   private java.lang.String eventName="DUMMY";
   private Request request;

   public Nodo()
   {
       
   }

   public java.lang.String getSys_id()
   {
      return this.sys_id;
   }
   
   

   public void setSys_id(java.lang.String sys_id)
   {
      this.sys_id = sys_id;
   }

   public java.lang.String getEventName()
   {
      return this.eventName;
   }

   public void setEventName(java.lang.String eventName)
   {
      this.eventName = eventName;
   }

   public Request getRequest()
   {
      return this.request;
   }

   public void setRequest(Request request)
   {
      this.request = request;
   }

   public Nodo(java.lang.String sys_id, java.lang.String eventName,
         Request request)
   {
      this.sys_id = sys_id;
      this.eventName = eventName;
      this.request = request;
   }

    public Nodo(java.lang.String sys_id)
   {
      this.sys_id = sys_id;
   }


    @Override
    public String toString() {
        if(request!= null)
        return "*("+this.sys_id+","+request.getEvent().getName()+" st: "+request.getStatusBRMS()+","+request+")";
        else
        return "("+this.sys_id+","+eventName+","+request+")";
        
    }

        @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof Nodo))
            return false;
        Nodo other = (Nodo) obj;
        if (sys_id == null) {
            if (other.sys_id != null)
                return false;
        } else if (!sys_id.equals(other.sys_id))
            return false;
        return true;
    }
    /**public int hashCode()
	{
		return sys_id.hashCode();
	}**/
  
}