package mx.com.ikusi.brms.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Response implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("resultado")
   private java.lang.String resultado;

   private java.lang.Integer tiempoEspera;
   
   private java.lang.String severidad;
   
   private java.lang.String descripcion;

   public Response()
   {
   }

   public java.lang.String getResultado()
   {
      return this.resultado;
   }

   public void setResultado(java.lang.String resultado)
   {
      this.resultado = resultado;
   }

   public java.lang.Integer getTiempoEspera()
   {
      return this.tiempoEspera;
   }

   public void setTiempoEspera(java.lang.Integer tiempoEspera)
   {
      this.tiempoEspera = tiempoEspera;
   }
   
   public java.lang.String getSeveridad()
   {
	   return this.severidad;
   }
   
   public void setSeveridad(java.lang.String severidad)
   {
	   this.severidad = severidad;
   }
   
   public java.lang.String getDescripcion()
   {
	   return this.descripcion;
   }
   
   public void setDescripcion(java.lang.String descripcion)
   {
	   this.descripcion = descripcion;
   }
   
   public void appendDescripcion(java.lang.String append){
		this.descripcion += "\n" + append;
	}

   public Response(java.lang.String resultado, java.lang.Integer tiempoEspera, java.lang.String severidad, java.lang.String descripcion)
   {
      this.resultado = resultado;
      this.tiempoEspera = tiempoEspera;
      this.severidad = severidad;
      this.descripcion = descripcion;
   }
   
   public String toString(){
	   return " Response[resultado="+ resultado +", descripcion="+ descripcion +"]";
   }

}