package mx.com.ikusi.brms.utils;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Constants {
	
	// Dispositivos
	public final static String DISP_SAI = "SAI";
	public final static String DISP_SS = "SS";
	public final static String DISP_RP = "RP";
	public final static String DISP_RS = "RS";
	public final static String DISP_SO = "SO";
	public final static String DISP_IDU = "IDU";
	
	// Estatus de dispositivo
	public final static String STAT_NEW = "INICIAL"; 		// Dispositivo nuevo
	public final static String STAT_SAVED = "SAVED"; 		// Guadado en memoria
	public final static String STAT_RETEST = "RETEST"; 		// Se vuelve a evaluar para verificar padres
	public final static String STAT_APPLY = "APPLY"; 		// El dispositivo esta listo para ser evaluado
	public final static String STAT_TO_WAIT_FOR_EVENT = "TO_WAIT_FOR_EVENT";
	public final static String STAT_RESOLVED="RESOLVED";
	public final static String STAT_TO_TIMER="TO_TIMER";
	public final static String STAT_ACTIVATE="STAT_ACTIVATE";
	public final static String STAT_TO_EVAL="TO_EVAL";
	public final static String STAT_DOUBLE_EVENT = "DOUBLE_EVENT";
	
	
	public final static String STAT_WAIT = "WAIT";  		// a FUSE - Tiene padres pero no aun no estan en memoria
	public final static String STAT_IGNORE = "NO_CREATE"; 	// a FUSE - No crea incidente
	public final static String STAT_CREATE = "CREATE"; 		// a FUSE - Si crea incidente
	public final static String STAT_UPDATE = "UPDATE";		// a FUSE - Actualizara el incidente
	public final static String STAT_MAIL = "MAIL";			// a FUSE - Envio de correo desde FUSE
	
	// Eventos
	public final static String EVENT_POWER_FAIL = "POWER_FAIL";
	public final static String EVENT_POWER_RESTORED = "POWER_RESTORED";
	public final static String EVENT_NODE_DOWN = "NODE_DOWN";
	public final static String EVENT_NODE_UP = "NODE_UP";
	
	
	
	//Severidad
	public final static String SEVERITY_1 = "1";
	public final static String SEVERITY_2 = "2";
	public final static String SEVERITY_3 = "3";
	
	public final static String INCIDENT_STATUS_RESOLVED = "6";

}